import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ToastProvider } from '@/providers/toast-provider';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/providers/theme-provider';
// import { Jersey_15 } from 'next/font/google';

const mainFont = localFont({
  src: '../fonts/IRANSansXV.woff2',
  variable: '--font-iransansxv',
  display: 'block',
});

// const jersey = Jersey_15({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'block',
//   variable: '--font-jersey',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa-Ir'>
      <body className={cn('font-sanX', mainFont.variable)}>
        <ThemeProvider attribute='class' disableTransitionOnChange enableSystem>
          <ToastProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
