import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ToastProvider } from '@/providers/toast-provider';
import { cn } from '@/libs/utils';

const mainFont = localFont({
  src: '../fonts/IRANSansXV.woff2',
  variable: '--font-iransansxv',
  display: 'block',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa-Ir'>
      <body className={cn('font-sanX', mainFont.variable)}>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
